# Setup

In [1]:
%matplotlib inline
import torch
import torch.nn as nn
import torch.nn.functional as F

# Hard code the data and seperate into x and y

In [2]:
train_data = torch.tensor(
    [
        [5,9,92],
        [4,8,91],
        [3,6,82],
        [5,8,95],
        [1,4,74],
        [2,6,75],
        [8,8,96],
        [7,8,94],
        [2,5,80],
        [6,9,91]
    ],
    dtype=torch.float
)

x, y = train_data[:, :2], train_data[:, -1]
y = y.view(len(y), 1)
y = y / 100.0

# Create a Module 
it has an input of two with 3 hidden units that are converted using the sigmoid function into 1 final unit

In [3]:
class Grades(nn.Module):           
  def __init__(self, D_in, D_out):
    super(Grades, self).__init__()
    self.lin1 = nn.Linear(D_in, 3, True)
    self.lin2 = nn.Linear(3, D_out, True)
  
  def forward(self, y):
    y = self.lin1(y)
    y = torch.sigmoid(y)
    y = self.lin2(y)
    return y

model = Grades(2, 1)

# Create loss and Optimize function

In [4]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)                 

# Run through 100 epochs
the loss on the last epoch was only 0.002604

In [5]:
epochs = 1000

for epoch in range(epochs):
  y_pred = model(x)
  loss = criterion(y_pred, y)
  if (epoch + 1) % 100 == 0:
    print('Epoch:', epoch + 1, '\tLoss:', loss.item())

  optimizer.zero_grad()                             
  loss.backward()                                    
  optimizer.step()                                    

Epoch: 100 	Loss: 0.06034904718399048
Epoch: 200 	Loss: 0.019226040691137314
Epoch: 300 	Loss: 0.007437414024025202
Epoch: 400 	Loss: 0.00406090822070837
Epoch: 500 	Loss: 0.00308579346165061
Epoch: 600 	Loss: 0.0027939036954194307
Epoch: 700 	Loss: 0.0026960638351738453
Epoch: 800 	Loss: 0.002653367118909955
Epoch: 900 	Loss: 0.0026264290791004896
Epoch: 1000 	Loss: 0.0026040845550596714


# Print out Predictions

In [6]:
x_dev = torch.tensor(
    [
        [3, 9],
        [1, 3],
        [7, 7],
        [4, 5],
        [8, 9]
    ],
    dtype=torch.float
)

with torch.no_grad():
  y_dev_pred = model(x_dev)

for x, y in zip(x_dev, y_dev_pred):
    print(x, ' prediction: ', y)

tensor([3., 9.])  prediction:  tensor([0.8733])
tensor([1., 3.])  prediction:  tensor([0.7819])
tensor([7., 7.])  prediction:  tensor([0.9010])
tensor([4., 5.])  prediction:  tensor([0.8629])
tensor([8., 9.])  prediction:  tensor([0.9092])
